#pragma once

#cmakedefine PROJECT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#cmakedefine PROJECT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#cmakedefine PROJECT_VERSION_PATCH @PROJECT_VERSION_PATCH@

#ifndef PROJECT_VERSION_MINOR
#define PROJECT_VERSION_MINOR 0
#endif

#ifndef PROJECT_VERSION_PATCH
#define PROJECT_VERSION_PATCH 0
#endif

#define VERSION_V v

#define API_VERSION_MAJOR VERSION_V ## PROJECT_VERSION_MAJOR